### ISSUE TITLE
HTTPS support.

### ISSUE THREAD

**Issue by PhonicUK** [jgauffin/Griffin.WebServer#13]
It'd be very nice to see HTTPS support like the old standalone webserver component had. Especially if it can be implemented using TLS. I'd be quite happy to throw some money at whoever can make this happen.

**Comment by jgauffin** [comment]
Here is how you do it in the Griffin.Framework branch:

```csharp
 var listener = new HttpListener();
            listener.ChannelFactory = new SecureTcpChannelFactory(new ServerSideSslStreamBuilder(certificate));
            listener.ClientConnected += OnConnect;
            listener.MessageReceived = OnMessage;
            listener.BodyDecoder = new CompositeIMessageSerializer();
            listener.Start(IPAddress.Any, 8083);
```

**Comment by cocowalla** [comment]
Does this support client certificates too?

**Comment by jgauffin** [comment]
Yes, use the [ClientSideSslStreamBuilder](https://github.com/jgauffin/Griffin.Framework/blob/master/src/Griffin.Framework/Griffin.Core/Net/Channels/ClientSideSslStreamBuilder.cs) instead.

**Comment by jgauffin** [comment]
Sorry, wrong of me. Just set the `UseClientCertificate` to true:

**Comment by cocowalla** [comment]
Great :)

What about performing authentication of the certificates provided by clients, is there an event handler to hook into? Or better yet, is there a sample that includes the use of client certificates?

**Comment by jgauffin** [comment]
Create `MyServerSideSslStreamBuilder` and override  `OnRemoteCertifiateValidation`

**Comment by jgauffin** [comment]
It works like described at MSDN: http://msdn.microsoft.com/en-us/library/system.net.security.remotecertificatevalidationcallback(v=vs.110).aspx

**Comment by PhonicUK** [comment]
Is the Griffin.Framework branch the same Griffin.Framework I can now see on NuGet?

**Comment by jgauffin** [comment]
yes

**Comment by jgauffin** [comment]
It's the official branch now
