### ISSUE TITLE
Closed loop when answering 'Range' requests from FileModule

### ISSUE THREAD

**Issue by PhonicUK** [jgauffin/Griffin.WebServer#22]
I'm still narrowing down the exact reproduction steps, but in the field users are finding that the web server enters a closed loop (and consequently munching on CPU time) when answering Range requests under certain circumstances.

In my local branch I've added an extra property to FileModule to simply disable this functionality cleanly, but I intend to find the root cause.

**Comment by jgauffin** [comment]
can you describe the solution?

**Comment by PhonicUK** [comment]
There wasn't actually an issue in the first place, bad report on my part.
