### ISSUE TITLE
ErrorModule bug

### ISSUE THREAD

**Issue by wo80** [jgauffin/Griffin.WebServer#26]
In method `SetErrorPage` (line 97): Instead of
```
httpContext.Response.Body = new MemoryStream();
httpContext.Response.Body.Write(bytes, 0, bytes.Length);
```
you should do
```
httpContext.Response.Body = new MemoryStream(bytes);
```
since `Body.Position` should be 0 when sending the response.

**EDIT**: Additionally, the `Response.ContentLength` should be set to the correct size.

**Comment by jgauffin** [comment]
corrected. thanks and apologies for the late reply.
