### ISSUE TITLE
Project not compiling

### ISSUE THREAD

**Issue by wo80** [jgauffin/Griffin.WebServer#38]
The build is failing since the last commit (6 month ago): DiskFileService and CompositeFileService do not implement IFileService (some interface methods were renamed).

Is this project still active?

Additionally, an updated nuget package would be highly appreciated!

**Comment by jgauffin** [comment]
I don't use it anymore. Pull requests are most welcome.

I can take a look at it next week + push a new package.

Most of my time goes to this: https://coderrapp.com

**Comment by wo80** [comment]
Yeah, I guess it's time to switch to Owin/Katana and the new WebApi.

Anyways, thanks a lot for this great project! I think it would be worthwhile making the build work and having a nuget package reflecting the latest changes.

**Comment by jgauffin** [comment]
corrected and pushed to nuget.
